//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealTimeUnit.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IRealTimeUnitService")]
    public interface IRealTimeUnitService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnitService/initialize", ReplyAction="http://tempuri.org/IRealTimeUnitService/initializeResponse")]
        bool initialize(string id, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnitService/initialize", ReplyAction="http://tempuri.org/IRealTimeUnitService/initializeResponse")]
        System.Threading.Tasks.Task<bool> initializeAsync(string id, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnitService/sendValueToAddress", ReplyAction="http://tempuri.org/IRealTimeUnitService/sendValueToAddressResponse")]
        void sendValueToAddress(string address, int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnitService/sendValueToAddress", ReplyAction="http://tempuri.org/IRealTimeUnitService/sendValueToAddressResponse")]
        System.Threading.Tasks.Task sendValueToAddressAsync(string address, int number);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRealTimeUnitServiceChannel : RealTimeUnit.ServiceReference.IRealTimeUnitService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RealTimeUnitServiceClient : System.ServiceModel.ClientBase<RealTimeUnit.ServiceReference.IRealTimeUnitService>, RealTimeUnit.ServiceReference.IRealTimeUnitService {
        
        public RealTimeUnitServiceClient() {
        }
        
        public RealTimeUnitServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RealTimeUnitServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeUnitServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeUnitServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool initialize(string id, string address) {
            return base.Channel.initialize(id, address);
        }
        
        public System.Threading.Tasks.Task<bool> initializeAsync(string id, string address) {
            return base.Channel.initializeAsync(id, address);
        }
        
        public void sendValueToAddress(string address, int number) {
            base.Channel.sendValueToAddress(address, number);
        }
        
        public System.Threading.Tasks.Task sendValueToAddressAsync(string address, int number) {
            return base.Channel.sendValueToAddressAsync(address, number);
        }
    }
}
