//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealTimeUnit.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IRealTimeUnitService")]
    public interface IRealTimeUnitService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnitService/Initialize", ReplyAction="http://tempuri.org/IRealTimeUnitService/InitializeResponse")]
        bool Initialize(string id, string address, byte[] signature, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnitService/Initialize", ReplyAction="http://tempuri.org/IRealTimeUnitService/InitializeResponse")]
        System.Threading.Tasks.Task<bool> InitializeAsync(string id, string address, byte[] signature, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnitService/SendValueToAddress", ReplyAction="http://tempuri.org/IRealTimeUnitService/SendValueToAddressResponse")]
        void SendValueToAddress(string address, int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnitService/SendValueToAddress", ReplyAction="http://tempuri.org/IRealTimeUnitService/SendValueToAddressResponse")]
        System.Threading.Tasks.Task SendValueToAddressAsync(string address, int number);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRealTimeUnitServiceChannel : RealTimeUnit.ServiceReference.IRealTimeUnitService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RealTimeUnitServiceClient : System.ServiceModel.ClientBase<RealTimeUnit.ServiceReference.IRealTimeUnitService>, RealTimeUnit.ServiceReference.IRealTimeUnitService {
        
        public RealTimeUnitServiceClient() {
        }
        
        public RealTimeUnitServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RealTimeUnitServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeUnitServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeUnitServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Initialize(string id, string address, byte[] signature, string message) {
            return base.Channel.Initialize(id, address, signature, message);
        }
        
        public System.Threading.Tasks.Task<bool> InitializeAsync(string id, string address, byte[] signature, string message) {
            return base.Channel.InitializeAsync(id, address, signature, message);
        }
        
        public void SendValueToAddress(string address, int number) {
            base.Channel.SendValueToAddress(address, number);
        }
        
        public System.Threading.Tasks.Task SendValueToAddressAsync(string address, int number) {
            return base.Channel.SendValueToAddressAsync(address, number);
        }
    }
}
